version: '3.7'


services:
  
  db:
    image: postgres:15
    restart: always 
    container_name: db
    command: -p 5435
    expose:
      - 5435
    ports:
      - "5435:5432"
    environment:
      - POSTGRES_PASSWORD=your_password
      - POSTGRES_USER=your_username
      - POSTGRES_DB=your_database
  
  api:
    container_name: qrmenu
    image: dchnkoo/qr-sys:0.0.1-ps
    command: ["./app.sh"]
    environment:
      - DATABASE_URL=postgresql+asyncpg://your_username:your_password@db:5435/your_database
      - DATABASE_URL_SYNC=postgresql://your_username:your_password@db:5435/your_database
    ports:
      - "8000:8080"
    depends_on:
      - db
