"""colum table -> table number

Revision ID: 82803f470b3b
Revises: 18736e18a34a
Create Date: 2024-01-24 23:02:02.530070

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '82803f470b3b'
down_revision: Union[str, None] = '18736e18a34a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tables', sa.Column('table_number', sa.Integer(), nullable=True))
    op.drop_column('tables', 'table')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tables', sa.Column('table', sa.INTEGER(), nullable=True))
    op.drop_column('tables', 'table_number')
    # ### end Alembic commands ###
